### ISSUE TITLE
Overview map

### ISSUE THREAD

**Issue by Quicksaver** [Quicksaver/React-User-Cards-Sample#4]
Display all the users on a map using [leaflet](http://leafletjs.com/).

**Comment by Quicksaver** [comment]
I'm either missing something very obvious with the geo locations, or they are just random coordinates...

**Comment by jolidog** [comment]
@Quicksaver Yep, they are random locations, lot's of drowning people...

**Comment by Quicksaver** [comment]
Not much I can do about it then.
